// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	langfuse "github.com/donaldgifford/server-price-tracker/pkg/observability/langfuse"
)

// MockClient is an autogenerated mock type for the Client type
type MockClient struct {
	mock.Mock
}

type MockClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockClient) EXPECT() *MockClient_Expecter {
	return &MockClient_Expecter{mock: &_m.Mock}
}

// CreateDatasetItem provides a mock function with given fields: ctx, datasetID, item
func (_m *MockClient) CreateDatasetItem(ctx context.Context, datasetID string, item *langfuse.DatasetItem) error {
	ret := _m.Called(ctx, datasetID, item)

	if len(ret) == 0 {
		panic("no return value specified for CreateDatasetItem")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *langfuse.DatasetItem) error); ok {
		r0 = rf(ctx, datasetID, item)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockClient_CreateDatasetItem_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateDatasetItem'
type MockClient_CreateDatasetItem_Call struct {
	*mock.Call
}

// CreateDatasetItem is a helper method to define mock.On call
//   - ctx context.Context
//   - datasetID string
//   - item *langfuse.DatasetItem
func (_e *MockClient_Expecter) CreateDatasetItem(ctx interface{}, datasetID interface{}, item interface{}) *MockClient_CreateDatasetItem_Call {
	return &MockClient_CreateDatasetItem_Call{Call: _e.mock.On("CreateDatasetItem", ctx, datasetID, item)}
}

func (_c *MockClient_CreateDatasetItem_Call) Run(run func(ctx context.Context, datasetID string, item *langfuse.DatasetItem)) *MockClient_CreateDatasetItem_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(*langfuse.DatasetItem))
	})
	return _c
}

func (_c *MockClient_CreateDatasetItem_Call) Return(_a0 error) *MockClient_CreateDatasetItem_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockClient_CreateDatasetItem_Call) RunAndReturn(run func(context.Context, string, *langfuse.DatasetItem) error) *MockClient_CreateDatasetItem_Call {
	_c.Call.Return(run)
	return _c
}

// CreateDatasetRun provides a mock function with given fields: ctx, run
func (_m *MockClient) CreateDatasetRun(ctx context.Context, run *langfuse.DatasetRun) error {
	ret := _m.Called(ctx, run)

	if len(ret) == 0 {
		panic("no return value specified for CreateDatasetRun")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *langfuse.DatasetRun) error); ok {
		r0 = rf(ctx, run)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockClient_CreateDatasetRun_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateDatasetRun'
type MockClient_CreateDatasetRun_Call struct {
	*mock.Call
}

// CreateDatasetRun is a helper method to define mock.On call
//   - ctx context.Context
//   - run *langfuse.DatasetRun
func (_e *MockClient_Expecter) CreateDatasetRun(ctx interface{}, run interface{}) *MockClient_CreateDatasetRun_Call {
	return &MockClient_CreateDatasetRun_Call{Call: _e.mock.On("CreateDatasetRun", ctx, run)}
}

func (_c *MockClient_CreateDatasetRun_Call) Run(run func(ctx context.Context, run *langfuse.DatasetRun)) *MockClient_CreateDatasetRun_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*langfuse.DatasetRun))
	})
	return _c
}

func (_c *MockClient_CreateDatasetRun_Call) Return(_a0 error) *MockClient_CreateDatasetRun_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockClient_CreateDatasetRun_Call) RunAndReturn(run func(context.Context, *langfuse.DatasetRun) error) *MockClient_CreateDatasetRun_Call {
	_c.Call.Return(run)
	return _c
}

// CreateTrace provides a mock function with given fields: ctx, name, metadata
func (_m *MockClient) CreateTrace(ctx context.Context, name string, metadata map[string]string) (langfuse.TraceHandle, error) {
	ret := _m.Called(ctx, name, metadata)

	if len(ret) == 0 {
		panic("no return value specified for CreateTrace")
	}

	var r0 langfuse.TraceHandle
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, map[string]string) (langfuse.TraceHandle, error)); ok {
		return rf(ctx, name, metadata)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, map[string]string) langfuse.TraceHandle); ok {
		r0 = rf(ctx, name, metadata)
	} else {
		r0 = ret.Get(0).(langfuse.TraceHandle)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, map[string]string) error); ok {
		r1 = rf(ctx, name, metadata)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockClient_CreateTrace_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateTrace'
type MockClient_CreateTrace_Call struct {
	*mock.Call
}

// CreateTrace is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
//   - metadata map[string]string
func (_e *MockClient_Expecter) CreateTrace(ctx interface{}, name interface{}, metadata interface{}) *MockClient_CreateTrace_Call {
	return &MockClient_CreateTrace_Call{Call: _e.mock.On("CreateTrace", ctx, name, metadata)}
}

func (_c *MockClient_CreateTrace_Call) Run(run func(ctx context.Context, name string, metadata map[string]string)) *MockClient_CreateTrace_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(map[string]string))
	})
	return _c
}

func (_c *MockClient_CreateTrace_Call) Return(_a0 langfuse.TraceHandle, _a1 error) *MockClient_CreateTrace_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockClient_CreateTrace_Call) RunAndReturn(run func(context.Context, string, map[string]string) (langfuse.TraceHandle, error)) *MockClient_CreateTrace_Call {
	_c.Call.Return(run)
	return _c
}

// LogGeneration provides a mock function with given fields: ctx, gen
func (_m *MockClient) LogGeneration(ctx context.Context, gen *langfuse.GenerationRecord) error {
	ret := _m.Called(ctx, gen)

	if len(ret) == 0 {
		panic("no return value specified for LogGeneration")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *langfuse.GenerationRecord) error); ok {
		r0 = rf(ctx, gen)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockClient_LogGeneration_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LogGeneration'
type MockClient_LogGeneration_Call struct {
	*mock.Call
}

// LogGeneration is a helper method to define mock.On call
//   - ctx context.Context
//   - gen *langfuse.GenerationRecord
func (_e *MockClient_Expecter) LogGeneration(ctx interface{}, gen interface{}) *MockClient_LogGeneration_Call {
	return &MockClient_LogGeneration_Call{Call: _e.mock.On("LogGeneration", ctx, gen)}
}

func (_c *MockClient_LogGeneration_Call) Run(run func(ctx context.Context, gen *langfuse.GenerationRecord)) *MockClient_LogGeneration_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*langfuse.GenerationRecord))
	})
	return _c
}

func (_c *MockClient_LogGeneration_Call) Return(_a0 error) *MockClient_LogGeneration_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockClient_LogGeneration_Call) RunAndReturn(run func(context.Context, *langfuse.GenerationRecord) error) *MockClient_LogGeneration_Call {
	_c.Call.Return(run)
	return _c
}

// Score provides a mock function with given fields: ctx, traceID, name, value, comment
func (_m *MockClient) Score(ctx context.Context, traceID string, name string, value float64, comment string) error {
	ret := _m.Called(ctx, traceID, name, value, comment)

	if len(ret) == 0 {
		panic("no return value specified for Score")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, float64, string) error); ok {
		r0 = rf(ctx, traceID, name, value, comment)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockClient_Score_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Score'
type MockClient_Score_Call struct {
	*mock.Call
}

// Score is a helper method to define mock.On call
//   - ctx context.Context
//   - traceID string
//   - name string
//   - value float64
//   - comment string
func (_e *MockClient_Expecter) Score(ctx interface{}, traceID interface{}, name interface{}, value interface{}, comment interface{}) *MockClient_Score_Call {
	return &MockClient_Score_Call{Call: _e.mock.On("Score", ctx, traceID, name, value, comment)}
}

func (_c *MockClient_Score_Call) Run(run func(ctx context.Context, traceID string, name string, value float64, comment string)) *MockClient_Score_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(float64), args[4].(string))
	})
	return _c
}

func (_c *MockClient_Score_Call) Return(_a0 error) *MockClient_Score_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockClient_Score_Call) RunAndReturn(run func(context.Context, string, string, float64, string) error) *MockClient_Score_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockClient creates a new instance of MockClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockClient {
	mock := &MockClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
