package main

import (
	"flag"
	"fmt"
	"os"
	"path/filepath"

	"gopkg.in/yaml.v3"

	"github.com/donaldgifford/server-price-tracker/tools/dashgen/rules"
)

const generatedHeader = "# Code generated by tools/dashgen; DO NOT EDIT.\n"

func main() {
	validateOnly := flag.Bool("validate", false, "validate generated artifacts without writing files")
	outputDir := flag.String("output", "", "override output directory")
	flag.Parse()

	cfg := DefaultConfig()
	if *outputDir != "" {
		cfg.OutputDir = *outputDir
	}

	if err := cfg.Validate(); err != nil {
		fmt.Fprintf(os.Stderr, "config error: %v\n", err)
		os.Exit(1)
	}

	if err := run(cfg, *validateOnly); err != nil {
		fmt.Fprintf(os.Stderr, "error: %v\n", err)
		os.Exit(1)
	}
}

func run(cfg Config, validateOnly bool) error {
	if validateOnly {
		fmt.Println("validation passed")
		return nil
	}

	if cfg.RulesEnabled {
		if err := generateRules(cfg); err != nil {
			return fmt.Errorf("generating rules: %w", err)
		}
	}

	return nil
}

func generateRules(cfg Config) error {
	promDir := filepath.Join(cfg.OutputDir, "prometheus")
	if err := os.MkdirAll(promDir, 0o755); err != nil {
		return fmt.Errorf("creating prometheus dir: %w", err)
	}

	recording := rules.RecordingRules()
	if err := writeYAML(promDir, "spt-recording-rules.yaml", recording); err != nil {
		return fmt.Errorf("writing recording rules: %w", err)
	}

	alerts := rules.AlertRules()
	if err := writeYAML(promDir, "spt-alerts.yaml", alerts); err != nil {
		return fmt.Errorf("writing alert rules: %w", err)
	}

	return nil
}

func writeYAML(dir, filename string, v any) error {
	data, err := yaml.Marshal(v)
	if err != nil {
		return fmt.Errorf("marshaling %s: %w", filename, err)
	}

	out := []byte(generatedHeader)
	out = append(out, data...)

	path := filepath.Join(dir, filename)
	if err := os.WriteFile(path, out, 0o644); err != nil {
		return fmt.Errorf("writing %s: %w", path, err)
	}

	fmt.Printf("wrote %s\n", path)
	return nil
}
