// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	notify "github.com/donaldgifford/server-price-tracker/internal/notify"
	mock "github.com/stretchr/testify/mock"
)

// MockNotifier is an autogenerated mock type for the Notifier type
type MockNotifier struct {
	mock.Mock
}

type MockNotifier_Expecter struct {
	mock *mock.Mock
}

func (_m *MockNotifier) EXPECT() *MockNotifier_Expecter {
	return &MockNotifier_Expecter{mock: &_m.Mock}
}

// SendAlert provides a mock function with given fields: ctx, alert
func (_m *MockNotifier) SendAlert(ctx context.Context, alert *notify.AlertPayload) error {
	ret := _m.Called(ctx, alert)

	if len(ret) == 0 {
		panic("no return value specified for SendAlert")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *notify.AlertPayload) error); ok {
		r0 = rf(ctx, alert)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockNotifier_SendAlert_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendAlert'
type MockNotifier_SendAlert_Call struct {
	*mock.Call
}

// SendAlert is a helper method to define mock.On call
//   - ctx context.Context
//   - alert *notify.AlertPayload
func (_e *MockNotifier_Expecter) SendAlert(ctx interface{}, alert interface{}) *MockNotifier_SendAlert_Call {
	return &MockNotifier_SendAlert_Call{Call: _e.mock.On("SendAlert", ctx, alert)}
}

func (_c *MockNotifier_SendAlert_Call) Run(run func(ctx context.Context, alert *notify.AlertPayload)) *MockNotifier_SendAlert_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*notify.AlertPayload))
	})
	return _c
}

func (_c *MockNotifier_SendAlert_Call) Return(_a0 error) *MockNotifier_SendAlert_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockNotifier_SendAlert_Call) RunAndReturn(run func(context.Context, *notify.AlertPayload) error) *MockNotifier_SendAlert_Call {
	_c.Call.Return(run)
	return _c
}

// SendBatchAlert provides a mock function with given fields: ctx, alerts, watchName
func (_m *MockNotifier) SendBatchAlert(ctx context.Context, alerts []notify.AlertPayload, watchName string) error {
	ret := _m.Called(ctx, alerts, watchName)

	if len(ret) == 0 {
		panic("no return value specified for SendBatchAlert")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []notify.AlertPayload, string) error); ok {
		r0 = rf(ctx, alerts, watchName)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockNotifier_SendBatchAlert_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendBatchAlert'
type MockNotifier_SendBatchAlert_Call struct {
	*mock.Call
}

// SendBatchAlert is a helper method to define mock.On call
//   - ctx context.Context
//   - alerts []notify.AlertPayload
//   - watchName string
func (_e *MockNotifier_Expecter) SendBatchAlert(ctx interface{}, alerts interface{}, watchName interface{}) *MockNotifier_SendBatchAlert_Call {
	return &MockNotifier_SendBatchAlert_Call{Call: _e.mock.On("SendBatchAlert", ctx, alerts, watchName)}
}

func (_c *MockNotifier_SendBatchAlert_Call) Run(run func(ctx context.Context, alerts []notify.AlertPayload, watchName string)) *MockNotifier_SendBatchAlert_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]notify.AlertPayload), args[2].(string))
	})
	return _c
}

func (_c *MockNotifier_SendBatchAlert_Call) Return(_a0 error) *MockNotifier_SendBatchAlert_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockNotifier_SendBatchAlert_Call) RunAndReturn(run func(context.Context, []notify.AlertPayload, string) error) *MockNotifier_SendBatchAlert_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockNotifier creates a new instance of MockNotifier. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockNotifier(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockNotifier {
	mock := &MockNotifier{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
