---
version: 2

builds:
  - id: server-price-tracker
    binary: server-price-tracker
    main: ./cmd/server-price-tracker
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0

  - id: spt
    binary: spt
    main: ./cmd/spt
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0

archives:
  - id: server
    ids:
      - server-price-tracker
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
    formats:
      - tar.gz
    files:
      - none*

  - id: cli
    ids:
      - spt
    name_template: "spt_{{ .Os }}_{{ .Arch }}"
    formats:
      - tar.gz
    files:
      - none*

checksum:
  name_template: 'checksums.txt'

signs:
  - artifacts: checksum
    args:
      - "--batch"
      - "--local-user"
      - "{{ .Env.GPG_FINGERPRINT }}"
      - "--output"
      - "${signature}"
      - "--detach-sign"
      - "${artifact}"

changelog:
  use: github
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
      - Merge pull request
      - Merge branch
  groups:
    - title: Features
      regexp: "^feat:"
      order: 0
    - title: Bug Fixes
      regexp: "^fix:"
      order: 1
    - title: Others
      order: 999

release:
  github:
    owner: donaldgifford
    name: server-price-tracker
  draft: false
  prerelease: auto
  mode: prepend
  header: |
    ## Release {{ .Tag }} ({{ .Date }})

    ### Installation

    #### Linux/macOS (Manual)
    ```bash
    # Server binary
    tar -xzf server-price-tracker_*.tar.gz
    mv server-price-tracker ~/.local/bin/

    # CLI client
    tar -xzf spt_*.tar.gz
    mv spt ~/.local/bin/
    ```

  footer: |
    ---
    **Full Changelog**: https://github.com/donaldgifford/server-price-tracker/compare/{{ .PreviousTag }}...{{ .Tag }}

snapshot:
  version_template: "{{ .Tag }}-dev"
