with-expecter: true
dir: "{{.InterfaceDir}}/mocks"
outpkg: "mocks"
filename: "mock_{{.InterfaceName | snakecase}}.go"
mockname: "Mock{{.InterfaceName}}"
packages:
  github.com/donaldgifford/server-price-tracker/internal/store:
    interfaces:
      Store:
  github.com/donaldgifford/server-price-tracker/internal/ebay:
    interfaces:
      EbayClient:
      TokenProvider:
  github.com/donaldgifford/server-price-tracker/internal/notify:
    interfaces:
      Notifier:
  github.com/donaldgifford/server-price-tracker/pkg/extract:
    interfaces:
      LLMBackend:
      Extractor:
