// Package components holds the templ components rendered by the alert
// review UI. The *.templ files are the source of truth; *_templ.go
// files are generated by `make templ-generate` and gitignored.
package components

import (
	"fmt"
	"net/url"
	"strconv"
)

// prevPageURL returns the existing query string with page decremented by 1.
// query is the raw query (no leading "?"); the result is suitable for an
// href attribute including the leading "?".
func prevPageURL(query string, page int) string {
	return pageURL(query, page-1)
}

// nextPageURL is prevPageURL's twin.
func nextPageURL(query string, page int) string {
	return pageURL(query, page+1)
}

func pageURL(rawQuery string, target int) string {
	if target < 1 {
		target = 1
	}
	values, err := url.ParseQuery(rawQuery)
	if err != nil {
		// Malformed query → drop it; the page link still works without filters.
		values = url.Values{}
	}
	values.Set("page", strconv.Itoa(target))
	return "?" + values.Encode()
}

// money formats a float price with currency, both used in the detail view.
func money(amount float64, currency string) string {
	if currency == "" {
		currency = "USD"
	}
	return fmt.Sprintf("%s %.2f", currency, amount)
}
