// Code generated by swaggo/swag. DO NOT EDIT.

package openapi

import "github.com/swaggo/swag/v2"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "components": {
        "schemas": {
            "github_com_donaldgifford_server-price-tracker_pkg_types.AttributeFilter": {
                "properties": {
                    "eq": {
                        "description": "exact match"
                    },
                    "in": {
                        "description": "value in set",
                        "items": {},
                        "type": "array",
                        "uniqueItems": false
                    },
                    "max": {
                        "description": "\u003c= this value",
                        "type": "number"
                    },
                    "min": {
                        "description": "\u003e= this value",
                        "type": "number"
                    }
                },
                "type": "object"
            },
            "github_com_donaldgifford_server-price-tracker_pkg_types.ComponentType": {
                "description": "Extracted data",
                "enum": [
                    "ram",
                    "drive",
                    "server",
                    "cpu",
                    "nic",
                    "other"
                ],
                "type": "string",
                "x-enum-varnames": [
                    "ComponentRAM",
                    "ComponentDrive",
                    "ComponentServer",
                    "ComponentCPU",
                    "ComponentNIC",
                    "ComponentOther"
                ]
            },
            "github_com_donaldgifford_server-price-tracker_pkg_types.Condition": {
                "enum": [
                    "new",
                    "like_new",
                    "used_working",
                    "for_parts",
                    "unknown"
                ],
                "type": "string",
                "x-enum-varnames": [
                    "ConditionNew",
                    "ConditionLikeNew",
                    "ConditionUsedWorking",
                    "ConditionForParts",
                    "ConditionUnknown"
                ]
            },
            "github_com_donaldgifford_server-price-tracker_pkg_types.Listing": {
                "properties": {
                    "attributes": {
                        "additionalProperties": {},
                        "type": "object"
                    },
                    "component_type": {
                        "$ref": "#/components/schemas/github_com_donaldgifford_server-price-tracker_pkg_types.ComponentType"
                    },
                    "condition_norm": {
                        "$ref": "#/components/schemas/github_com_donaldgifford_server-price-tracker_pkg_types.Condition"
                    },
                    "condition_raw": {
                        "type": "string"
                    },
                    "currency": {
                        "type": "string"
                    },
                    "ebay_item_id": {
                        "type": "string"
                    },
                    "extraction_confidence": {
                        "type": "number"
                    },
                    "first_seen_at": {
                        "type": "string"
                    },
                    "id": {
                        "type": "string"
                    },
                    "image_url": {
                        "type": "string"
                    },
                    "item_url": {
                        "type": "string"
                    },
                    "listed_at": {
                        "description": "Timestamps",
                        "type": "string"
                    },
                    "listing_type": {
                        "$ref": "#/components/schemas/github_com_donaldgifford_server-price-tracker_pkg_types.ListingType"
                    },
                    "price": {
                        "description": "Pricing",
                        "type": "number"
                    },
                    "product_key": {
                        "type": "string"
                    },
                    "quantity": {
                        "type": "integer"
                    },
                    "score": {
                        "description": "Scoring",
                        "type": "integer"
                    },
                    "score_breakdown": {
                        "items": {
                            "type": "integer"
                        },
                        "type": "array",
                        "uniqueItems": false
                    },
                    "seller_feedback_pct": {
                        "type": "number"
                    },
                    "seller_feedback_score": {
                        "type": "integer"
                    },
                    "seller_name": {
                        "description": "Seller",
                        "type": "string"
                    },
                    "seller_top_rated": {
                        "type": "boolean"
                    },
                    "shipping_cost": {
                        "type": "number"
                    },
                    "sold_at": {
                        "type": "string"
                    },
                    "sold_price": {
                        "type": "number"
                    },
                    "title": {
                        "type": "string"
                    },
                    "updated_at": {
                        "type": "string"
                    }
                },
                "type": "object"
            },
            "github_com_donaldgifford_server-price-tracker_pkg_types.ListingType": {
                "enum": [
                    "auction",
                    "buy_it_now",
                    "best_offer"
                ],
                "type": "string",
                "x-enum-varnames": [
                    "ListingAuction",
                    "ListingBuyItNow",
                    "ListingBestOffer"
                ]
            },
            "github_com_donaldgifford_server-price-tracker_pkg_types.Watch": {
                "properties": {
                    "category_id": {
                        "type": "string"
                    },
                    "component_type": {
                        "$ref": "#/components/schemas/github_com_donaldgifford_server-price-tracker_pkg_types.ComponentType"
                    },
                    "created_at": {
                        "type": "string"
                    },
                    "enabled": {
                        "type": "boolean"
                    },
                    "filters": {
                        "$ref": "#/components/schemas/github_com_donaldgifford_server-price-tracker_pkg_types.WatchFilters"
                    },
                    "id": {
                        "type": "string"
                    },
                    "name": {
                        "type": "string"
                    },
                    "score_threshold": {
                        "type": "integer"
                    },
                    "search_query": {
                        "type": "string"
                    },
                    "updated_at": {
                        "type": "string"
                    }
                },
                "type": "object"
            },
            "github_com_donaldgifford_server-price-tracker_pkg_types.WatchFilters": {
                "properties": {
                    "attribute_filters": {
                        "additionalProperties": {
                            "$ref": "#/components/schemas/github_com_donaldgifford_server-price-tracker_pkg_types.AttributeFilter"
                        },
                        "description": "Component-specific attribute filters (flexible)\nThese match against the extracted attributes JSON.\nSupports exact match, min/max ranges.",
                        "type": "object"
                    },
                    "conditions": {
                        "description": "Condition",
                        "items": {
                            "$ref": "#/components/schemas/github_com_donaldgifford_server-price-tracker_pkg_types.Condition"
                        },
                        "type": "array",
                        "uniqueItems": false
                    },
                    "price_max": {
                        "description": "Price",
                        "type": "number"
                    },
                    "price_min": {
                        "type": "number"
                    },
                    "seller_min_feedback": {
                        "description": "Seller",
                        "type": "integer"
                    },
                    "seller_min_feedback_pct": {
                        "type": "number"
                    },
                    "seller_top_rated_only": {
                        "type": "boolean"
                    }
                },
                "type": "object"
            },
            "internal_api_handlers.ErrorResponse": {
                "properties": {
                    "error": {
                        "example": "something went wrong",
                        "type": "string"
                    }
                },
                "type": "object"
            },
            "internal_api_handlers.StatusResponse": {
                "properties": {
                    "status": {
                        "example": "ok",
                        "type": "string"
                    }
                },
                "type": "object"
            },
            "internal_api_handlers.extractRequest": {
                "properties": {
                    "item_specifics": {
                        "additionalProperties": {
                            "type": "string"
                        },
                        "type": "object"
                    },
                    "title": {
                        "example": "Samsung 32GB DDR4 2666MHz ECC REG Server RAM",
                        "type": "string"
                    }
                },
                "type": "object"
            },
            "internal_api_handlers.extractResponse": {
                "properties": {
                    "attributes": {
                        "additionalProperties": {},
                        "type": "object"
                    },
                    "component_type": {
                        "$ref": "#/components/schemas/github_com_donaldgifford_server-price-tracker_pkg_types.ComponentType"
                    },
                    "product_key": {
                        "example": "ram:ddr4:ecc_reg:32gb:2666",
                        "type": "string"
                    }
                },
                "type": "object"
            },
            "internal_api_handlers.listingsResponse": {
                "properties": {
                    "limit": {
                        "type": "integer"
                    },
                    "listings": {
                        "items": {
                            "$ref": "#/components/schemas/github_com_donaldgifford_server-price-tracker_pkg_types.Listing"
                        },
                        "type": "array",
                        "uniqueItems": false
                    },
                    "offset": {
                        "type": "integer"
                    },
                    "total": {
                        "type": "integer"
                    }
                },
                "type": "object"
            },
            "internal_api_handlers.searchRequest": {
                "properties": {
                    "category_id": {
                        "example": "170083",
                        "type": "string"
                    },
                    "filters": {
                        "additionalProperties": {
                            "type": "string"
                        },
                        "type": "object"
                    },
                    "limit": {
                        "example": 10,
                        "type": "integer"
                    },
                    "query": {
                        "example": "DDR4 ECC REG 32GB server RAM",
                        "type": "string"
                    },
                    "sort": {
                        "example": "newlyListed",
                        "type": "string"
                    }
                },
                "type": "object"
            },
            "internal_api_handlers.setEnabledRequest": {
                "properties": {
                    "enabled": {
                        "example": true,
                        "type": "boolean"
                    }
                },
                "type": "object"
            }
        }
    },
    "info": {
        "contact": {
            "name": "Donald Gifford",
            "url": "https://github.com/donaldgifford/server-price-tracker"
        },
        "description": "{{escape .Description}}",
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "title": "{{.Title}}",
        "version": "{{.Version}}"
    },
    "externalDocs": {
        "description": "",
        "url": ""
    },
    "paths": {
        "/api/v1/baselines/refresh": {
            "post": {
                "description": "Recomputes percentile price baselines for all product keys.",
                "responses": {
                    "200": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/internal_api_handlers.StatusResponse"
                                }
                            }
                        },
                        "description": "OK"
                    },
                    "500": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/internal_api_handlers.ErrorResponse"
                                }
                            }
                        },
                        "description": "Internal Server Error"
                    }
                },
                "summary": "Refresh price baselines",
                "tags": [
                    "scoring"
                ]
            }
        },
        "/api/v1/extract": {
            "post": {
                "description": "Uses the configured LLM backend to classify the component type and extract structured attributes from a listing title.",
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "oneOf": [
                                    {
                                        "type": "object"
                                    },
                                    {
                                        "$ref": "#/components/schemas/internal_api_handlers.extractRequest",
                                        "summary": "body",
                                        "description": "Listing title and optional item specifics"
                                    }
                                ]
                            }
                        }
                    },
                    "description": "Listing title and optional item specifics",
                    "required": true
                },
                "responses": {
                    "200": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/internal_api_handlers.extractResponse"
                                }
                            }
                        },
                        "description": "OK"
                    },
                    "400": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/internal_api_handlers.ErrorResponse"
                                }
                            }
                        },
                        "description": "Bad Request"
                    },
                    "500": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/internal_api_handlers.ErrorResponse"
                                }
                            }
                        },
                        "description": "Internal Server Error"
                    }
                },
                "summary": "Extract attributes from a listing title",
                "tags": [
                    "extract"
                ]
            }
        },
        "/api/v1/ingest": {
            "post": {
                "description": "Runs the full ingestion pipeline: fetch listings from eBay, extract attributes via LLM, score, and alert.",
                "responses": {
                    "200": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/internal_api_handlers.StatusResponse"
                                }
                            }
                        },
                        "description": "OK"
                    },
                    "500": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/internal_api_handlers.ErrorResponse"
                                }
                            }
                        },
                        "description": "Internal Server Error"
                    }
                },
                "summary": "Trigger manual ingestion",
                "tags": [
                    "ingest"
                ]
            }
        },
        "/api/v1/listings": {
            "get": {
                "description": "Returns listings with optional filters for component type, score range, and pagination.",
                "parameters": [
                    {
                        "description": "Filter by component type",
                        "in": "query",
                        "name": "component_type",
                        "schema": {
                            "enum": [
                                "ram",
                                "drive",
                                "server",
                                "cpu",
                                "nic",
                                "other"
                            ],
                            "type": "string"
                        }
                    },
                    {
                        "description": "Filter by product key",
                        "in": "query",
                        "name": "product_key",
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "description": "Minimum composite score",
                        "in": "query",
                        "name": "min_score",
                        "schema": {
                            "type": "integer"
                        }
                    },
                    {
                        "description": "Maximum composite score",
                        "in": "query",
                        "name": "max_score",
                        "schema": {
                            "type": "integer"
                        }
                    },
                    {
                        "description": "Number of results (default 50)",
                        "in": "query",
                        "name": "limit",
                        "schema": {
                            "type": "integer"
                        }
                    },
                    {
                        "description": "Pagination offset",
                        "in": "query",
                        "name": "offset",
                        "schema": {
                            "type": "integer"
                        }
                    },
                    {
                        "description": "Sort field",
                        "in": "query",
                        "name": "order_by",
                        "schema": {
                            "enum": [
                                "score",
                                "price",
                                "first_seen_at"
                            ],
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/internal_api_handlers.listingsResponse"
                                }
                            }
                        },
                        "description": "OK"
                    },
                    "400": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/internal_api_handlers.ErrorResponse"
                                }
                            }
                        },
                        "description": "Bad Request"
                    },
                    "500": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/internal_api_handlers.ErrorResponse"
                                }
                            }
                        },
                        "description": "Internal Server Error"
                    }
                },
                "summary": "List listings",
                "tags": [
                    "listings"
                ]
            }
        },
        "/api/v1/listings/{id}": {
            "get": {
                "description": "Returns a single listing by its UUID.",
                "parameters": [
                    {
                        "description": "Listing UUID",
                        "in": "path",
                        "name": "id",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/github_com_donaldgifford_server-price-tracker_pkg_types.Listing"
                                }
                            }
                        },
                        "description": "OK"
                    },
                    "400": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/internal_api_handlers.ErrorResponse"
                                }
                            }
                        },
                        "description": "Bad Request"
                    },
                    "404": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/internal_api_handlers.ErrorResponse"
                                }
                            }
                        },
                        "description": "Not Found"
                    }
                },
                "summary": "Get a listing by ID",
                "tags": [
                    "listings"
                ]
            }
        },
        "/api/v1/rescore": {
            "post": {
                "description": "Recalculates composite scores for all listings using current baselines.",
                "responses": {
                    "200": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "additionalProperties": {},
                                    "type": "object"
                                }
                            }
                        },
                        "description": "scored count"
                    },
                    "500": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/internal_api_handlers.ErrorResponse"
                                }
                            }
                        },
                        "description": "Internal Server Error"
                    }
                },
                "summary": "Re-score all listings",
                "tags": [
                    "scoring"
                ]
            }
        },
        "/api/v1/search": {
            "post": {
                "description": "Proxies a search request to the eBay Browse API and returns raw listings.",
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "oneOf": [
                                    {
                                        "type": "object"
                                    },
                                    {
                                        "$ref": "#/components/schemas/internal_api_handlers.searchRequest",
                                        "summary": "body",
                                        "description": "Search parameters"
                                    }
                                ]
                            }
                        }
                    },
                    "description": "Search parameters",
                    "required": true
                },
                "responses": {
                    "200": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "additionalProperties": {},
                                    "type": "object"
                                }
                            }
                        },
                        "description": "listings, total, has_more"
                    },
                    "400": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/internal_api_handlers.ErrorResponse"
                                }
                            }
                        },
                        "description": "Bad Request"
                    },
                    "502": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/internal_api_handlers.ErrorResponse"
                                }
                            }
                        },
                        "description": "Bad Gateway"
                    }
                },
                "summary": "Search eBay listings",
                "tags": [
                    "search"
                ]
            }
        },
        "/api/v1/watches": {
            "get": {
                "description": "Returns all watches, optionally filtered by enabled status.",
                "parameters": [
                    {
                        "description": "Filter by enabled status",
                        "in": "query",
                        "name": "enabled",
                        "schema": {
                            "enum": [
                                "true",
                                "false"
                            ],
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "items": {
                                        "$ref": "#/components/schemas/github_com_donaldgifford_server-price-tracker_pkg_types.Watch"
                                    },
                                    "type": "array"
                                }
                            }
                        },
                        "description": "OK"
                    },
                    "500": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/internal_api_handlers.ErrorResponse"
                                }
                            }
                        },
                        "description": "Internal Server Error"
                    }
                },
                "summary": "List watches",
                "tags": [
                    "watches"
                ]
            },
            "post": {
                "description": "Creates a new watch with the given configuration.",
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "oneOf": [
                                    {
                                        "type": "object"
                                    },
                                    {
                                        "$ref": "#/components/schemas/github_com_donaldgifford_server-price-tracker_pkg_types.Watch",
                                        "summary": "watch",
                                        "description": "Watch to create"
                                    }
                                ]
                            }
                        }
                    },
                    "description": "Watch to create",
                    "required": true
                },
                "responses": {
                    "201": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/github_com_donaldgifford_server-price-tracker_pkg_types.Watch"
                                }
                            }
                        },
                        "description": "Created"
                    },
                    "400": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/internal_api_handlers.ErrorResponse"
                                }
                            }
                        },
                        "description": "Bad Request"
                    },
                    "500": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/internal_api_handlers.ErrorResponse"
                                }
                            }
                        },
                        "description": "Internal Server Error"
                    }
                },
                "summary": "Create a watch",
                "tags": [
                    "watches"
                ]
            }
        },
        "/api/v1/watches/{id}": {
            "delete": {
                "description": "Deletes a watch by its UUID.",
                "parameters": [
                    {
                        "description": "Watch UUID",
                        "in": "path",
                        "name": "id",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "500": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/internal_api_handlers.ErrorResponse"
                                }
                            }
                        },
                        "description": "Internal Server Error"
                    }
                },
                "summary": "Delete a watch",
                "tags": [
                    "watches"
                ]
            },
            "get": {
                "description": "Returns a single watch by its UUID.",
                "parameters": [
                    {
                        "description": "Watch UUID",
                        "in": "path",
                        "name": "id",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/github_com_donaldgifford_server-price-tracker_pkg_types.Watch"
                                }
                            }
                        },
                        "description": "OK"
                    },
                    "404": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/internal_api_handlers.ErrorResponse"
                                }
                            }
                        },
                        "description": "Not Found"
                    }
                },
                "summary": "Get a watch by ID",
                "tags": [
                    "watches"
                ]
            },
            "put": {
                "description": "Updates an existing watch by its UUID.",
                "parameters": [
                    {
                        "description": "Watch UUID",
                        "in": "path",
                        "name": "id",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "oneOf": [
                                    {
                                        "type": "object"
                                    },
                                    {
                                        "$ref": "#/components/schemas/github_com_donaldgifford_server-price-tracker_pkg_types.Watch",
                                        "summary": "watch",
                                        "description": "Updated watch"
                                    }
                                ]
                            }
                        }
                    },
                    "description": "Updated watch",
                    "required": true
                },
                "responses": {
                    "200": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/github_com_donaldgifford_server-price-tracker_pkg_types.Watch"
                                }
                            }
                        },
                        "description": "OK"
                    },
                    "400": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/internal_api_handlers.ErrorResponse"
                                }
                            }
                        },
                        "description": "Bad Request"
                    },
                    "500": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/internal_api_handlers.ErrorResponse"
                                }
                            }
                        },
                        "description": "Internal Server Error"
                    }
                },
                "summary": "Update a watch",
                "tags": [
                    "watches"
                ]
            }
        },
        "/api/v1/watches/{id}/enabled": {
            "put": {
                "description": "Sets the enabled status of a watch.",
                "parameters": [
                    {
                        "description": "Watch UUID",
                        "in": "path",
                        "name": "id",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "oneOf": [
                                    {
                                        "type": "object"
                                    },
                                    {
                                        "$ref": "#/components/schemas/internal_api_handlers.setEnabledRequest",
                                        "summary": "body",
                                        "description": "Enabled status"
                                    }
                                ]
                            }
                        }
                    },
                    "description": "Enabled status",
                    "required": true
                },
                "responses": {
                    "200": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/internal_api_handlers.StatusResponse"
                                }
                            }
                        },
                        "description": "OK"
                    },
                    "400": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/internal_api_handlers.ErrorResponse"
                                }
                            }
                        },
                        "description": "Bad Request"
                    },
                    "500": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/internal_api_handlers.ErrorResponse"
                                }
                            }
                        },
                        "description": "Internal Server Error"
                    }
                },
                "summary": "Enable or disable a watch",
                "tags": [
                    "watches"
                ]
            }
        },
        "/healthz": {
            "get": {
                "description": "Returns 200 if the process is running.",
                "responses": {
                    "200": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/internal_api_handlers.StatusResponse"
                                }
                            }
                        },
                        "description": "OK"
                    }
                },
                "summary": "Liveness check",
                "tags": [
                    "health"
                ]
            }
        },
        "/readyz": {
            "get": {
                "description": "Returns 200 if the database is reachable, 503 otherwise.",
                "responses": {
                    "200": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/internal_api_handlers.StatusResponse"
                                }
                            }
                        },
                        "description": "OK"
                    },
                    "503": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/internal_api_handlers.StatusResponse"
                                }
                            }
                        },
                        "description": "Service Unavailable"
                    }
                },
                "summary": "Readiness check",
                "tags": [
                    "health"
                ]
            }
        }
    },
    "openapi": "3.1.0",
    "servers": [
        {
            "description": "Local development server",
            "url": "http://localhost:8080"
        }
    ]
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0.0",
	Title:            "Server Price Tracker API",
	Description:      "API for monitoring eBay server hardware listings, extracting structured attributes via LLM, scoring deals, and sending alerts.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
