// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	extract "github.com/donaldgifford/server-price-tracker/pkg/extract"
)

// MockLLMBackend is an autogenerated mock type for the LLMBackend type
type MockLLMBackend struct {
	mock.Mock
}

type MockLLMBackend_Expecter struct {
	mock *mock.Mock
}

func (_m *MockLLMBackend) EXPECT() *MockLLMBackend_Expecter {
	return &MockLLMBackend_Expecter{mock: &_m.Mock}
}

// Generate provides a mock function with given fields: ctx, req
func (_m *MockLLMBackend) Generate(ctx context.Context, req extract.GenerateRequest) (extract.GenerateResponse, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for Generate")
	}

	var r0 extract.GenerateResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, extract.GenerateRequest) (extract.GenerateResponse, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, extract.GenerateRequest) extract.GenerateResponse); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Get(0).(extract.GenerateResponse)
	}

	if rf, ok := ret.Get(1).(func(context.Context, extract.GenerateRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockLLMBackend_Generate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Generate'
type MockLLMBackend_Generate_Call struct {
	*mock.Call
}

// Generate is a helper method to define mock.On call
//   - ctx context.Context
//   - req extract.GenerateRequest
func (_e *MockLLMBackend_Expecter) Generate(ctx interface{}, req interface{}) *MockLLMBackend_Generate_Call {
	return &MockLLMBackend_Generate_Call{Call: _e.mock.On("Generate", ctx, req)}
}

func (_c *MockLLMBackend_Generate_Call) Run(run func(ctx context.Context, req extract.GenerateRequest)) *MockLLMBackend_Generate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(extract.GenerateRequest))
	})
	return _c
}

func (_c *MockLLMBackend_Generate_Call) Return(_a0 extract.GenerateResponse, _a1 error) *MockLLMBackend_Generate_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockLLMBackend_Generate_Call) RunAndReturn(run func(context.Context, extract.GenerateRequest) (extract.GenerateResponse, error)) *MockLLMBackend_Generate_Call {
	_c.Call.Return(run)
	return _c
}

// Name provides a mock function with no fields
func (_m *MockLLMBackend) Name() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Name")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockLLMBackend_Name_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Name'
type MockLLMBackend_Name_Call struct {
	*mock.Call
}

// Name is a helper method to define mock.On call
func (_e *MockLLMBackend_Expecter) Name() *MockLLMBackend_Name_Call {
	return &MockLLMBackend_Name_Call{Call: _e.mock.On("Name")}
}

func (_c *MockLLMBackend_Name_Call) Run(run func()) *MockLLMBackend_Name_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockLLMBackend_Name_Call) Return(_a0 string) *MockLLMBackend_Name_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockLLMBackend_Name_Call) RunAndReturn(run func() string) *MockLLMBackend_Name_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockLLMBackend creates a new instance of MockLLMBackend. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockLLMBackend(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockLLMBackend {
	mock := &MockLLMBackend{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
