// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/donaldgifford/server-price-tracker/pkg/types"

	mock "github.com/stretchr/testify/mock"
)

// MockExtractor is an autogenerated mock type for the Extractor type
type MockExtractor struct {
	mock.Mock
}

type MockExtractor_Expecter struct {
	mock *mock.Mock
}

func (_m *MockExtractor) EXPECT() *MockExtractor_Expecter {
	return &MockExtractor_Expecter{mock: &_m.Mock}
}

// Classify provides a mock function with given fields: ctx, title
func (_m *MockExtractor) Classify(ctx context.Context, title string) (domain.ComponentType, error) {
	ret := _m.Called(ctx, title)

	if len(ret) == 0 {
		panic("no return value specified for Classify")
	}

	var r0 domain.ComponentType
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (domain.ComponentType, error)); ok {
		return rf(ctx, title)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) domain.ComponentType); ok {
		r0 = rf(ctx, title)
	} else {
		r0 = ret.Get(0).(domain.ComponentType)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, title)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockExtractor_Classify_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Classify'
type MockExtractor_Classify_Call struct {
	*mock.Call
}

// Classify is a helper method to define mock.On call
//   - ctx context.Context
//   - title string
func (_e *MockExtractor_Expecter) Classify(ctx interface{}, title interface{}) *MockExtractor_Classify_Call {
	return &MockExtractor_Classify_Call{Call: _e.mock.On("Classify", ctx, title)}
}

func (_c *MockExtractor_Classify_Call) Run(run func(ctx context.Context, title string)) *MockExtractor_Classify_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockExtractor_Classify_Call) Return(_a0 domain.ComponentType, _a1 error) *MockExtractor_Classify_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockExtractor_Classify_Call) RunAndReturn(run func(context.Context, string) (domain.ComponentType, error)) *MockExtractor_Classify_Call {
	_c.Call.Return(run)
	return _c
}

// ClassifyAndExtract provides a mock function with given fields: ctx, title, itemSpecifics
func (_m *MockExtractor) ClassifyAndExtract(ctx context.Context, title string, itemSpecifics map[string]string) (domain.ComponentType, map[string]interface{}, error) {
	ret := _m.Called(ctx, title, itemSpecifics)

	if len(ret) == 0 {
		panic("no return value specified for ClassifyAndExtract")
	}

	var r0 domain.ComponentType
	var r1 map[string]interface{}
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string, map[string]string) (domain.ComponentType, map[string]interface{}, error)); ok {
		return rf(ctx, title, itemSpecifics)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, map[string]string) domain.ComponentType); ok {
		r0 = rf(ctx, title, itemSpecifics)
	} else {
		r0 = ret.Get(0).(domain.ComponentType)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, map[string]string) map[string]interface{}); ok {
		r1 = rf(ctx, title, itemSpecifics)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(map[string]interface{})
		}
	}

	if rf, ok := ret.Get(2).(func(context.Context, string, map[string]string) error); ok {
		r2 = rf(ctx, title, itemSpecifics)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockExtractor_ClassifyAndExtract_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ClassifyAndExtract'
type MockExtractor_ClassifyAndExtract_Call struct {
	*mock.Call
}

// ClassifyAndExtract is a helper method to define mock.On call
//   - ctx context.Context
//   - title string
//   - itemSpecifics map[string]string
func (_e *MockExtractor_Expecter) ClassifyAndExtract(ctx interface{}, title interface{}, itemSpecifics interface{}) *MockExtractor_ClassifyAndExtract_Call {
	return &MockExtractor_ClassifyAndExtract_Call{Call: _e.mock.On("ClassifyAndExtract", ctx, title, itemSpecifics)}
}

func (_c *MockExtractor_ClassifyAndExtract_Call) Run(run func(ctx context.Context, title string, itemSpecifics map[string]string)) *MockExtractor_ClassifyAndExtract_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(map[string]string))
	})
	return _c
}

func (_c *MockExtractor_ClassifyAndExtract_Call) Return(_a0 domain.ComponentType, _a1 map[string]interface{}, _a2 error) *MockExtractor_ClassifyAndExtract_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockExtractor_ClassifyAndExtract_Call) RunAndReturn(run func(context.Context, string, map[string]string) (domain.ComponentType, map[string]interface{}, error)) *MockExtractor_ClassifyAndExtract_Call {
	_c.Call.Return(run)
	return _c
}

// Extract provides a mock function with given fields: ctx, componentType, title, itemSpecifics
func (_m *MockExtractor) Extract(ctx context.Context, componentType domain.ComponentType, title string, itemSpecifics map[string]string) (map[string]interface{}, error) {
	ret := _m.Called(ctx, componentType, title, itemSpecifics)

	if len(ret) == 0 {
		panic("no return value specified for Extract")
	}

	var r0 map[string]interface{}
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.ComponentType, string, map[string]string) (map[string]interface{}, error)); ok {
		return rf(ctx, componentType, title, itemSpecifics)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.ComponentType, string, map[string]string) map[string]interface{}); ok {
		r0 = rf(ctx, componentType, title, itemSpecifics)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]interface{})
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.ComponentType, string, map[string]string) error); ok {
		r1 = rf(ctx, componentType, title, itemSpecifics)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockExtractor_Extract_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Extract'
type MockExtractor_Extract_Call struct {
	*mock.Call
}

// Extract is a helper method to define mock.On call
//   - ctx context.Context
//   - componentType domain.ComponentType
//   - title string
//   - itemSpecifics map[string]string
func (_e *MockExtractor_Expecter) Extract(ctx interface{}, componentType interface{}, title interface{}, itemSpecifics interface{}) *MockExtractor_Extract_Call {
	return &MockExtractor_Extract_Call{Call: _e.mock.On("Extract", ctx, componentType, title, itemSpecifics)}
}

func (_c *MockExtractor_Extract_Call) Run(run func(ctx context.Context, componentType domain.ComponentType, title string, itemSpecifics map[string]string)) *MockExtractor_Extract_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.ComponentType), args[2].(string), args[3].(map[string]string))
	})
	return _c
}

func (_c *MockExtractor_Extract_Call) Return(_a0 map[string]interface{}, _a1 error) *MockExtractor_Extract_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockExtractor_Extract_Call) RunAndReturn(run func(context.Context, domain.ComponentType, string, map[string]string) (map[string]interface{}, error)) *MockExtractor_Extract_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockExtractor creates a new instance of MockExtractor. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockExtractor(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockExtractor {
	mock := &MockExtractor{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
