// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	ebay "github.com/donaldgifford/server-price-tracker/internal/ebay"
	mock "github.com/stretchr/testify/mock"
)

// MockEbayClient is an autogenerated mock type for the EbayClient type
type MockEbayClient struct {
	mock.Mock
}

type MockEbayClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockEbayClient) EXPECT() *MockEbayClient_Expecter {
	return &MockEbayClient_Expecter{mock: &_m.Mock}
}

// Search provides a mock function with given fields: ctx, req
func (_m *MockEbayClient) Search(ctx context.Context, req ebay.SearchRequest) (*ebay.SearchResponse, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for Search")
	}

	var r0 *ebay.SearchResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, ebay.SearchRequest) (*ebay.SearchResponse, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, ebay.SearchRequest) *ebay.SearchResponse); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ebay.SearchResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, ebay.SearchRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockEbayClient_Search_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Search'
type MockEbayClient_Search_Call struct {
	*mock.Call
}

// Search is a helper method to define mock.On call
//   - ctx context.Context
//   - req ebay.SearchRequest
func (_e *MockEbayClient_Expecter) Search(ctx interface{}, req interface{}) *MockEbayClient_Search_Call {
	return &MockEbayClient_Search_Call{Call: _e.mock.On("Search", ctx, req)}
}

func (_c *MockEbayClient_Search_Call) Run(run func(ctx context.Context, req ebay.SearchRequest)) *MockEbayClient_Search_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(ebay.SearchRequest))
	})
	return _c
}

func (_c *MockEbayClient_Search_Call) Return(_a0 *ebay.SearchResponse, _a1 error) *MockEbayClient_Search_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockEbayClient_Search_Call) RunAndReturn(run func(context.Context, ebay.SearchRequest) (*ebay.SearchResponse, error)) *MockEbayClient_Search_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockEbayClient creates a new instance of MockEbayClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockEbayClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockEbayClient {
	mock := &MockEbayClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
